# Student Alcohol Consumption

### Introduction:

This time you will download a dataset from the UCI.

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv).

### Step 3. Assign it to a variable called df.

In [3]:
# !curl -O "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv"
# df=pd.read_csv('student-mat.csv',index_col='',parse_dates='')
df=pd.read_csv('student-mat.csv')

### Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

In [4]:
# df.loc[:,'school':'guardian']
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    str
 1   sex         395 non-null    str
 2   age         395 non-null    int64
 3   address     395 non-null    str
 4   famsize     395 non-null    str
 5   Pstatus     395 non-null    str
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    str
 9   Fjob        395 non-null    str
 10  reason      395 non-null    str
 11  guardian    395 non-null    str
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    str
 16  famsup      395 non-null    str
 17  paid        395 non-null    str
 18  activities  395 non-null    str
 19  nursery     395 non-null    str
 20  higher      395 non-null    str
 21  internet    395 non-null    str
 22  romantic    395 non-null    str
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), str(17)
memory usage: 102.0 KB

### Step 5. Create a lambda function that will capitalize strings.

In [5]:
# func=lambda string_:string_.str.upper()
# df.apply(func)

# func=lambda string_:
# func=lambda series:series[series.dtypes==str]
# df.apply(func)

func=lambda series:series.str.upper()
df.astype(str).apply(func)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,AT_HOME,TEACHER,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,AT_HOME,OTHER,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,AT_HOME,OTHER,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,HEALTH,SERVICES,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,OTHER,OTHER,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,SERVICES,SERVICES,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,SERVICES,SERVICES,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,OTHER,OTHER,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,SERVICES,OTHER,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,OTHER,AT_HOME,...,3,2,3,3,3,5,5,8,9,9

### Step 6. Capitalize both Mjob and Fjob

In [6]:
# func=lambda series:
# df[['Mjob','Fjob']].str.upper()
func=lambda series:series.str.upper()
df[['Mjob','Fjob']].apply(func)

         Mjob      Fjob
0     AT_HOME   TEACHER
1     AT_HOME     OTHER
2     AT_HOME     OTHER
3      HEALTH  SERVICES
4       OTHER     OTHER
..        ...       ...
390  SERVICES  SERVICES
391  SERVICES  SERVICES
392     OTHER     OTHER
393  SERVICES     OTHER
394     OTHER   AT_HOME

[395 rows x 2 columns]

### Step 7. Print the last elements of the data set.

In [7]:
df.iloc[-1,-1]

np.int64(9)

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and capitalize Mjob and Fjob.

In [8]:
func=lambda series:series.str.upper()
df[['Mjob','Fjob']]=df[['Mjob','Fjob']].apply(func)
# df

### Step 9. Create a function called majority that returns a boolean value to a new column called legal_drinker (Consider majority as older than 17 years old)

In [9]:
import pandas as pd
##creating filter
##boolean value
#function

# filter_=(df['age']>17==True)
# df[filter_]

# def majority(df:pd.DataFrame):
#     filter_=df['age']>17
    
#     if df['age']>17:
#         df[filter_]
#     else:
#         df[~filter_]
#     # df['legal_drinker']=np.concatenate([df[filter_]['age'],df[~filter_]['age']],axis=0)
#     return df['legal_drinker']

# majority(df)

# def majority(series)->bool:
#     filter_=series['age']>17
#     if filter_:
#         return True
#     else:
#         return False
# # df
# #creating new features that called legal_drinker
# # df.apply(majority)
# filter_=df['age']>17
# # df[filter_]['age']
# df['legal_drinker']=df[filter_]['age']==True
# df['legal_drinker']

### Step 10. Multiply every number of the dataset by 10. 
##### I know this makes no sense, don't forget it is just an exercise

In [12]:
import numpy as np
import pandas as pd

#defining filter_ that type integer
# filter_=df.dtypes==np.int64
# df[filter_]
# df[df.dtypes==np.int64]
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    str
 1   sex         395 non-null    str
 2   age         395 non-null    int64
 3   address     395 non-null    str
 4   famsize     395 non-null    str
 5   Pstatus     395 non-null    str
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    str
 9   Fjob        395 non-null    str
 10  reason      395 non-null    str
 11  guardian    395 non-null    str
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    str
 16  famsup      395 non-null    str
 17  paid        395 non-null    str
 18  activities  395 non-null    str
 19  nursery     395 non-null    str
 20  higher      395 non-null    str
 21  internet    395 non-null    str
 22  romantic    395 non-null    str
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), str(17)
memory usage: 102.0 KB