# Pokemon

### Introduction:

This time you will create the data.



### Step 1. Import the necessary libraries

In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

import numpy as np
import pandas as pd

### Step 2. Create a data dictionary that looks like the DataFrame below

In [3]:
data={
    'evolution':['lvysaur','Charmeleon','Wartortle','Metapod'],
    'hp':[45,39,44,45],
    'pokedox':[True,False,True,False],
    'type':['grass','fire','water','bug']
    }
data

{'evolution': ['lvysaur', 'Charmeleon', 'Wartortle', 'Metapod'],
 'hp': [45, 39, 44, 45],
 'pokedox': [True, False, True, False],
 'type': ['grass', 'fire', 'water', 'bug']}

### Step 3. Assign it to a variable called pokemon

In [4]:
pokemon=pd.DataFrame(data)
pokemon.head()

    evolution  hp  pokedox   type
0     lvysaur  45     True  grass
1  Charmeleon  39    False   fire
2   Wartortle  44     True  water
3     Metapod  45    False    bug

### Step 4. Ops...it seems the DataFrame columns are in alphabetical order. Place  the order of the columns as name, type, hp, evolution, pokedex

In [ ]:
# creating new dataframe

pokemon=pd.DataFrame(
    {
        'name':[None,None,None,None],
        'type':pokemon.type,
        'hp':pokemon.hp,
        'evolution':pokemon.evolution,
        'pokedox':pokemon.pokedox
                }
)

df

   name   type  hp   evolution  pokedox
0  None  grass  45     lvysaur     True
1  None   fire  39  Charmeleon    False
2  None  water  44   Wartortle     True
3  None    bug  45     Metapod    False

### Step 5. Add another column called place, and insert what you have in mind.

In [6]:
pokemon['place']=np.arange(0,4,1)

### Step 6. Present the type of each column

In [7]:
pokemon.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   evolution  4 non-null      str
 1   hp         4 non-null      int64
 2   pokedox    4 non-null      bool
 3   type       4 non-null      str
 4   place      4 non-null      int64
dtypes: bool(1), int64(2), str(2)
memory usage: 264.0 bytes

### BONUS: Create your own question and answer it.